- .travis.yml
See also https://github.com/codeforamerica/projectmonitor/commit/d861b8aaa60e3377bd056b8fb4afd1eb5e06e27c
> Fixed webhook URL for project monitor

- README.md
- app.py
- tests.py
Switched to using HTTP basic auth and new required configuration variable.
Closes #336.
> Updated people auth

- app.py
- static/css/style.css
- templates/brigade_list.html
- templates/index.html
We should probably split out the javascript for the map generation, but I wasn't sure how to, since flask has to pass in the brigades.  We could make an endpoint to serve up the brigades in json format, but that's for later.
> Created brigade list

- templates/checkin.html
Forgot to git add on my previous push!
> added the "checkin.html" file

- brigade/templates/civic_json.html
- brigade/views.py
Allows you to edit the pull request message when submitting a civic.json to a project.
> Edit civic json commit message

- .travis.yml
- brigade/templates/base.html
- brigade/templates/projects.html
Works locally and I saw the search come through on Google Analytics Real Time.
> Add google analytics to Project Search

- brigade/views.py
- tests/tests.py
Fixes the occasional GitHub error **"Branch add-civic-json-file not found"**, reported when attempting to create a civic.json pull request.
Closes #412
> Handle civic json GitHub errors

- brigade/views.py
- tests/tests.py
The verify_repo wasn't accurately checking for the existence of a branch. I fixed it and re-structured the corresponding test.
> Fix branch checking

- brigade/static/css/style.css
- brigade/templates/civic_json.html
Simplifies and redesigns the civic json builder page.
> Civicjson builder design

- brigade/templates/tools/index.html
Puts in latest tools in the page
> Updated tools page to new In-kind

- README.md
Going forward, I'll assume the responsibility for handling inbound
contact requests for this repo.
> Add myself as a point of contact for this repo

- brigade/templates/map.html
The links are currently loading inside the iframe.
> Open brigade profile links on map embed in new tabs

- brigade/templates/about.html
- brigade/templates/base.html
- brigade/templates/brigade.html
- brigade/templates/projects.html
- filters/__init__.py
For SEO this will be crucial. I might have gone a bit crazy adding
Jinja filters for this stuff.
> Add <meta> description to brigade pages

- brigade/templates/about.html
Update text on about page
Small improvements to layout
This addresses issue #452
> Update about page

- brigade/templates/about.html
- brigade/templates/index.html
It's not a good idea to use modifiers on their own - let's add the base 'list' class.
> Fix typo for consistency with BEM convention

- brigade/templates/about.html
This video is a functional replacement of the old video, serving the
same purpose of explaining the Brigade program to an audience that is
not familiar. It seems like a natural replacement for the old video on
the "About Us" page.
cc @GovInTrenches @ErieMeyer
> Use the (awesome) new Brigade overview video

- cfapi/__init__.py
The inner and outer `if` statements both look for 'Brigade' in 'Tags'.
> Clean up unnecessary repetition

- brigade/__init__.py
- brigade/static/js/application.js
- brigade/views.py
- tests/tests.py
The commit messages should be a good read 📖 👀  ; this series of commits tackles the items I checked off here:
https://trello.com/c/dRGmAEQA/28-redirects-404s
> Fix redirects and 404

- brigade/templates/events.html
Open Data Day has passed, so commenting it out on the Events page for now.
> Hide Open Data Day on list of Key Dates

- brigade/static/js/application.js
- brigade/templates/brigade.html
Mapbox is an in-kind sponsor of CfA, so we should use their products
where possible. This also creates visual consistency with the homepage's
map!
> Replace Google Map on brigade profiles with Mapbox

- brigade/templates/free_software.html
Somehow, I forgot to do this! :flushed:
Thanks for the reminder, Mikel.
> Add Mapbox to our Software page

- brigade/templates/resources.html
This new version of the playbook has been recently updated by Veronica!
> Update Brigade website's Playbook link

- README.md
> Clarify relationship between Chi Hack Night and Open Gov Hack Night

- brigade/static/js/application.js
- brigade/static/scss/core/_variables.scss
- brigade/static/scss/pages/_home.scss
- brigade/templates/base.html
This adds the mobile nav menu by copying the requisite JS.
This requires yet another change to the style guide in order to allow
customizability of the mobile nav background color.
> Add Mobile nav

- brigade/static/scss/molecules/_card.scss
- brigade/templates/brigade.html
- brigade/templates/styleguide.html
- Add card samples to the style guide
- Re-introduce the "card--horizontal" variant for the "event card"
section of the brigade profile
- Remove unused classes from buttons
> Update event card section of Brigade profile page

- brigade/static/scss/molecules/_searchbar.scss
- brigade/templates/projects.html
(This PR depends on the v4-subhero branch/PR.)
This page needed considerable love. There's probably more to do here,
but this is a good start.
Before:
After:
> Update old project finder page to new style guide

- brigade/templates/free_software.html
- brigade/templates/free_software/aws.html
- brigade/templates/free_software/bizspark.html
- brigade/templates/free_software/carto.html
- brigade/templates/free_software/github.html
- brigade/templates/free_software/gsuite.html
- brigade/templates/free_software/heroku.html
- brigade/templates/free_software/mapbox.html
- brigade/templates/free_software/meetup.html
- brigade/templates/free_software/slack.html
- brigade/templates/free_software/twilio.html
- yarn.lock
These pages could still use another pass, but here's a good starting point.
Also upgrades the style guide to 4.0.4.
> Update Free software pages

- brigade/templates/resources.html
- Use message component for 'Notice a resource that's missing?' and 'New to organizing?' messages.
- Move messages into a new slab to distinguish them from the resource cards.
> Use message component for messages on resources page

- brigade/templates/brigade.html
- brigade/templates/resources.html
The <small> text is very hard to read.
> Remove <small> tags from resource cards and profile 'next event' card

- brigade/templates/events.html
- yarn.lock
We've decided on dates, so let's communicate them via our Events page.
> Add 2019 Events to Events page

- brigade/templates/code_of_conduct.html
- Add an above-the-fold message encouraging reports
- Add instructions on emails to report to (in addition to email
template)
> Make the "Reporting" section more prominent

- brigade/templates/financial_administration.html
- brigade/templates/resources.html
- brigade/views.py
This page still has some visual polish to do, but I want to push it soon
to get some feedback.
> Add initial version of the "financial administration" page

- brigade/templates/financial_administration.html
- New address
- We refund donations to FS and Partner brigades now
> Update financial administration page with new policies for 2019

- brigade/templates/project_showcase.html
> Add HRTB.us to Transportation

- README.md
- brigade/templates/events.html
We're pretty sure about these dates, let's get them on the website.
> Update events page for 2020 dates

- brigade/templates/priority_action_areas/record_clearance.html
- brigade/templates/priority_action_areas/voting_rights.html
- Add project canvases to Record Clearance and Voting Areas pages
- Also add some additional copy to those pages
> Add project canvases to Priority Action Areas
