codeforamerica/brigade

- README-Project-Search.md
- brigade/templates/projects.html
- brigade/templates/stages.html
- brigade/views.py
- tests/tests.py
The linked stages will now use the `status` parameter instead of the `q` search param. This more exactly matches the cfapi and also returns projects with a stage in order of last_updated. Very nice. I included tests but they are just testing mock responses, not the cfapi, which is of questionable utility.
@tmaybe want to review?
> Stages use status now instead of search

- brigade/views.py
- tests/tests.py
Adds mock responses for the civic.json pull request flow when the submitter has write access to the target repository, and tests the successful navigation of that flow.
> Improve civic.json test coverage

- brigade/templates/projects_embed.html
Addresses #437 where the src attribute in the iframe to share projects would drop "https://codeforamerica.org" if the user switches to another organization.
> Fix iframe src attribute

- brigade/static/css/style.css
- brigade/templates/projectmonitor.html
This PR is just a front-end fix to make the project boxes display at even heights.
Before:
After:
This change makes use of display: table-cell, which is supported by IE 8 and above. I wish there wasn't as much JS in the view itself, but that could be something to refactor later.
> Project monitor ui

- brigade/views.py
- tests/tests.py
In case you happen to go to https://brigade.codeforamerica.org, it
should redirect you to /brigade instead of failing. In the future we'll
probably want to resolve the routing situation.
This is a quick fix until I can remove the `/brigade` from the URLs.
> Add redirect from / -> /brigade

- brigade/__init__.py
- brigade/templates/base.html
- brigade/views.py
- brigade/wsgi.py
- cfapi/__init__.py
- manage.py
- tests/tests.py
This has a few motivations:
- the views.py file is pretty massive
- this allows them to be unit tested easier
- extracting these methods will allow them to be reused elsewhere in the
app (outside of the `brigade` blueprint)
- it makes the responsibility clear
This required some modifications to the tests, including one test which
accidentally was un-stubbed and reaching out to the internet.
> Extract CfAPI methods into a separate module

- app.json
- brigade/__init__.py
- brigade/sitemap.py
- brigade/static/robots.txt
- brigade/views.py
- requirements.txt
- tests/tests.py
This will help search engines discover content on the site. By using the
library flask-sitemap, we can create this without doing too much XML
hacking.
Note that this requires SITEMAP_URL_SCHEME environment variable to be
set to "https" in order to generate secure links by default.
> Add sitemap.xml to Brigade site

- brigade/templates/organize/index.html
Let's remove the link to This Week in Civic Tech from the organize page for now.
> Remove reference to This Week in Civic Tech

- brigade/static/js/application.js
- brigade/templates/base.html
- brigade/templates/brigade.html
- brigade/templates/brigade_list.html
- brigade/templates/index.html
- brigade/templates/numbers.html
- brigade/templates/projects.html
- brigade/templates/rsvps.html
This begins a trend to move all JS into an application bundle file,
rather than inserting it dynamically on each page. Child views are still
responsible for calling that page's JS initialization.
I also removed a bunch of JS that seemed unused, and moved the remainder
to the bottom of the <body> (instead of in the `<head>` and outside the
`<body>` -- two locations to avoid putting JS!)
>  Move almost all JS into one "application" file 

- brigade/static/css/style.css
This is a temporary fix until we rework the site's navigation. It addresses an issue on narrower screens where the header overlaps the main content.
> Fix header overlap issue on mobile

- brigade/static/js/application.js
- brigade/templates/about.html
- brigade/templates/base.html
- brigade/templates/organize/checklist.html
- brigade/templates/organize/index.html
- brigade/templates/organize/playbook.html
- brigade/templates/projects.html
This adds a global event handler that tracks all clicks. The default
behavior is to track an event with category 'Link Click', action
'click', and label equal to the link's destination href.
However, this can be changed like so:
- if the link is to a different origin, the category changes to
'External Link Click'
- if the link has a "title" attribute, that is used in place of the
"href" attribute for the event's label
- if the link has a "data-analytics-category" attribute, that is used in
place of the default 'Link Click' category (the intent of this is to
allow a product area like the Project Finder to keep its analytics
separate from the rest of the site).
[Closes #469]
> Automatically track all internal & external clicks

- webpack.config.js
I noticed that the CSS filename we were serving didn't change between
multiple deploys, which seems wrong. Whenever the content of the CSS
file changes, so too should its filename.
The problem seems to stem from the ExtractTextPlugin. [Its docs recommend
"[contenthash]" instead of "[chunkhash]"][1]. (Perhaps the "[chunkhash]"
was was always evaluating to the hash of an empty string after the text
had been extracted?)
Note that this appears to currently work fine for javascript.
[1]: https://github.com/webpack-contrib/extract-text-webpack-plugin#options
> Make sure to bust CSS cache when webpack build changes

- filters/__init__.py
The filter function was using the 'type' field from the API, but we've
switched to using 'tags' instead. As a result, some brigade pages (where
the Brigade Information doesn't have a type defined) weren't loading --
for example, [Code for Muskogee](https://brigade.codeforamerica.org/brigade/Code-for-Muskogee/). This fixes that error.
> Update event description filter to use 'tags' rather than 'type'

- brigade/static/js/application.js
Before:
After:
The default mapbox styling uses a pure-white (#fff) background for land
areas. User feedback indicated that this makes the navigation controls
hard to see.
By removing the existing tileLayer and adding a "styleLayer" (a class
which extends tileLayer - see [1]), we can make the map a bit more
stylish with a theme that uses a grey for the countries. [Here's a list
of all public styles.][2]
[1]: https://www.mapbox.com/mapbox.js/api/v3.1.1/l-mapbox-stylelayer/
[2]: https://github.com/mapbox/mapbox-gl-styles
> Use "bright-v8" instead of default mapbox style layer

- brigade/sitemap.py
- brigade/views.py
- package.json
- webpack.config.js
- yarn.lock
The robots.txt file was not being served because the static folder was
not configured in the "brigade" app because of the way that blueprints
get initialized.
By using the copy-webpack-plugin to copy the file and retain a constant
name, we can serve it up from next to the sitemap.
> Fix robots.txt

- brigade/views.py
The project list pagination URLs were wrong because they didn't use the
`url_for` helper. Using this helper results in less code since it will
handle the cases of a brigade/non-brigade project pages automatically.
The code was also broken in creating a malformed URL when paginating to
the second page of a brigade's projects (i.e.
http://brigade.codeforamerica.org/brigades/Code-for-San-Jose/projects?page=2
would request
http://api.codeforamerica.org/api/organizations/Code-for-San-Jose/projects&page=1)
To fix this, I used a proper query string encoding method instead of
string concatenation.
> Fix projects pagination URLs

- brigade/templates/free_software.html
We're rolling out G Suite now to brigades. Let's add this to the
software page!
> Add link to G Suite to software page

- brigade/views.py
- tests/tests.py
This is a quick DRYing up of our various redirect methods. I googled
around for a better way to do this with flask but didn't find one.
This adds a decorator which dynamically creates these handler methods
and registers them as a route.
(note- eventually this should be extracted from the views.py file to somewhere else)
> Add `@redirect_from` decorator to handle redirects

- brigade/static/scss/molecules/_alert.scss
- brigade/templates/events.html
This adds an `.alert__icon` element and displays it neatly alongside the alert content. Also makes some minor visual improvements.
Before: 
After:
> Small style adjustments to Alert component

- brigade/templates/index.html
It's not clear at the moment from the home page where to go to start a new brigade. This commit adds a little alert box with a link to the [Start a Brigade page](https://www.codeforamerica.org/how-tos-1/how-tos-start-a-brigade) on the CfA website, to help the user get started.
> Add 'start a new brigade' alert to homepage

- brigade/templates/events.html
This adds a new section with an embedded Google Calendar that includes
network-wide events like workshops and other meetings.
This also adds a page navigation for the two sections: Key Dates, and
Workshops and Meetings.
> Add Workshops and Meetings calendar to Events page

- brigade/sitemap.py
- brigade/static/scss/core/_utilities.scss
- brigade/static/scss/molecules/_nav.scss
- brigade/static/scss/pages/_brigade-list.scss
- brigade/static/scss/style.scss
- brigade/templates/base.html
- brigade/templates/brigade_list.html
- brigade/views.py
- cfapi/__init__.py
- tests/tests.py
At the moment, the only way to navigate to a brigade profile is through
the map on the home page. During earlier user testing, some participants
mentioned that they would prefer to use a text listing of the brigades
for navigation, or struggled to use the map.
This adds a new page with a text listing of all the official brigades.
Brigades are grouped by State and displayed alphabetically. The State
abbreviation for each brigade is inferred from its `city` property. When
the City spans two states, as is the case with Code for Kansas City,
it is displayed under both states -- i.e. Kansas and Missouri.
> Add text listing of all brigades

- brigade/templates/events.html
This adds the correct description.
> Fix typo with BRigade Congress description

- brigade/static/js/application.js
- brigade/static/scss/pages/_home.scss
- brigade/templates/index.html
At certain screen widths, the homepage 'hero' banner rendered poorly with some strange clearfix issues and overlapping content.
This commit removes the Javascript that made the map take up the full screen height and makes changes to the homepage styling to render the hero banner neatly using flexbox.
We're planning some big changes to the homepage in the near-future, so this is a quick-fix right now to get things to render properly and not break at certain screen widths.
> Fix homepage hero banner so it displays properly at all screen widths

- brigade/templates/base.html
- brigade/templates/brigade.html
This represents Fritz and my best guess at a better place for the
"Donate" button that is more intuitive that you're donating to a
specific brigade.
This is slightly WIP -- I'll be testing it tonight, and also the copy
could likely use some attention from others.
> Move "Donate" link from header to brigade page

- brigade/templates/base.html
This reverts commit 4c229c5724f8bdc6d70f18b6861f9fad7d74f551.
Applications for the fellowship are over now -- we can remove the
pre-header message!
> Revert "Add Community Fellowship pre-header message"

- manage.py
This had been causing a deprecation warning for some time. Switching out
the import to match the current documentation on
https://flask-script.readthedocs.io/en/latest/ seems to do the trick.
> Fix tests by importing correct package

- brigade/static/scss/core/_base.scss
- brigade/static/scss/molecules/_alert.scss
- brigade/static/scss/molecules/_card.scss
- brigade/static/scss/molecules/_list-group.scss
- brigade/static/scss/style.scss
- brigade/templates/base.html
- brigade/templates/brigade.html
- brigade/templates/project_showcase.html
- brigade/views.py
We want to add a new Project Showcase page to show off exemplar projects from across the Network that demonstrate a commitment to Code for America's values, clean code, and good documentation. This adds a simple version of the new page as an MVP, and has been through a few rounds of user testing. This should be a good starting point that we can continue iterating over and adding additional projects to.
> Add a Project Showcase page

- brigade/templates/project_showcase.html
This PR adds some example housing projects to the showcase, and links to the Brigade Housing project workshop video on Youtube. 
It also embeds the two brigade projects workshop Youtube videos on the Project Showcase page.
> Add housing section to Project Showcase

- brigade/static/scss/molecules/_message.scss
- brigade/static/scss/style.scss
- brigade/templates/brigade_list.html
- brigade/templates/events.html
- brigade/templates/index.html
- brigade/templates/resources_videos.html
- brigade/templates/styleguide.html
As we're updating the Brigade site to use the v4 styleguide, we realized that the site stylesheets and
the v4 styleguide both have an 'alert' component. @tdooner and I discussed it and realized that,
where we've been using the 'alert' component, it's been to provide information rather than to
'alert' the user of anything. Accordingly we agreed to rename the component to 'message'.
This commit also cleans up the SCSS for the message component slightly.
> Rename 'alert' component to 'message'

- brigade/static/scss/core/_variables.scss
- brigade/static/scss/molecules/_message.scss
- brigade/static/scss/style.scss
- brigade/templates/base.html
- brigade/templates/project_showcase.html
This PR updates the the layout of the Project Showcase page to work with the v4 style guide. It also updates the `message` component to be more subtle and more consistent with the look of the main website and the v4 style guide. 
The update Project Showcase page looks like this:
> Update project showcase to work with v4 style guide

- .sass-lint.yml
- .scss-lint.yml
- package.json
- yarn.lock
This adds an SCSS lint config file, adapting the one used on GetCalFresh, so we can write clean, consistent and easy-to-read SCSS. @tdooner and I discussed our SCSS syntax preferences, and we both lean towards BEM with alphatically sorted properties.
> Add SCSS lint config

- brigade/templates/base.html
- brigade/templates/events.html
1. Add a sitewide header for it
2. Update its entry on the events page to link to the official site, and its description to match our existing marketing copy.
> Update "Brigade Congress" on brigade website

- cfapi/__init__.py
- tests/tests.py
These collaborations have city fields that are actually states. We can
lump the brigade into that state by checking for this case.
For "Open NC Collaborative" they were already on the map, but missing
from the list because their state wasn't in the list of states.
> Handle statewide collaborations when pulling from cfapi

- brigade/static/js/application.js
- brigade/static/scss/organisms/_subhero.scss
- brigade/templates/base.html
- brigade/templates/events.html
The feedback from the team was around two points:
1. the site felt a bit too spacious (too much padding)
2. the map interaction on the homepage was tripped up by scroll wheels
To the first point, by making the subhero not a "slab" anymore removes its padding-bottom and looks pretty good.
The map interaction was tricky, but by disabling scroll zooming until a `mousemove` event is triggered, I think will work pretty well.
> Reduce subhero padding-bottom and improve map interaction

- app.json
- brigade/templates/about.html
- brigade/templates/code_of_conduct.html
- brigade/templates/resources.html
- brigade/views.py
We want to create a CoC page that is a bit more intuitive and visually
capable than a Github repo. Changes from Github will have to be
syndicated here manually.
> Add Code of Conduct page to Brigade Website

- brigade/templates/resources.html
We wanted to link to these as well, though creating a full card for them
seems a bit odd since they are different than the other resources listed
already. I've broken them into a separate section of other links that
may be useful.
Although this approach doesn't scale for _many_ links, it'll work to get
a few more links on the page and improve the SEO of the Discourse.
> Add "Other Links" section for Discourse & Fellowship

- brigade/templates/404.html
- tests/tests.py
Addresses Issue #588 where 500 errors are being sent on pages that apparently should be a 404.
The 500 was due to a broken URL reverse, that appears to have been residual from a move from /brigades/ to brigade.codeforamerica.org. The 404 page test was still passing because it referenced the 404 on the /brigades/ URL.
Link and test case have been updated.
> Issue #588 - server error on 404 pages that are not under /brigades/ subfolder

- brigade/templates/free_software.html
- brigade/templates/free_software/bizspark.html
According to the last person who tried to claim this inkind:
"It seems that Microsoft has closed BizSpark last year and changed their
target audience:
> What happened to BizSpark and BizSpark Plus?
> As of February 2018, we are no longer accepting applications for the
> BizSpark or BizSpark Plus programs. We are accepting applications for
> the Microsoft for Startups program and any startup currently enrolled in
> BizSpark or BizSpark Plus will be able to access their benefits for the
> balance of the time outlined at the outset of their membership. If you
> were, or are, a member of BizSpark and you fit the guidelines for
> Microsoft for Startups’ new qualified offers, we invite you to apply.
> For additional questions and support resources, please feel free to
> contact us: BizSpark …
> Remove Bizspark/Azure from free software pages

- brigade/views.py
- cfapi/__init__.py
- tests/tests.py
This will prevent discontinuity in Google Search results, etc., when a
Brigade renames.
> Add redirect from "previous_names" to current name

- brigade/templates/base.html
- brigade/templates/events.html
This relates to a request from Em Burnett, Sr. Manager of Network Communications.
- Renaming "Events" page -> "Brigade calendar"
- Removing Open Data Day as a key event
- Add message to bottom for Brigade leaders to check Discourse for important dates
- Rearrange section structure, so that Workshops+Meetings calendar is first section, and Key Dates is second
> Rename and rearrange Events page, and add copy
